apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::247344596475:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::247344596475:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DJHYERRCC2SW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-09T10:57:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1487"
  uid: f824cc58-2bd8-45ba-a72e-2c9ba215a91c